stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"
          pip install -r requirements.txt
          nostests -vd
          bash <(curl -s https://codecov.io/bash)

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  image: python:3.5
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master